#!/bin/bash

mkdir HL1-8

curl -L  -o HL1-8/HL1_R1_paired.fastq.gz
curl -L  -o HL1-8/HL1_R2_paired.fastq.gz
curl -L  -o HL1-8/HL2_R1_paired.fastq.gz
curl -L  -o HL1-8/HL2_R2_paired.fastq.gz
curl -L  -o HL1-8/HL3_R1_paired.fastq.gz
curl -L  -o HL1-8/HL3_R2_paired.fastq.gz
curl -L  -o HL1-8/HL4_R1_paired.fastq.gz
curl -L  -o HL1-8/HL4_R2_paired.fastq.gz
curl -L  -o HL1-8/HL5_R1_paired.fastq.gz
curl -L  -o HL1-8/HL5_R2_paired.fastq.gz
curl -L  -o HL1-8/HL6_R1_paired.fastq.gz
curl -L  -o HL1-8/HL6_R2_paired.fastq.gz
curl -L  -o HL1-8/HL7_R1_paired.fastq.gz
curl -L  -o HL1-8/HL7_R2_paired.fastq.gz
curl -L  -o HL1-8/HL8_R1_paired.fastq.gz
curl -L  -o HL1-8/HL8_R2_paired.fastq.gz
